[package]
name = "lazy-exclusive"
version = "0.1.0"
edition = "2024"

[target.'cfg(target_os = "windows")'.dependencies]
windows-link = { version = "0.1.1", optional = true }

[features]
use-locks = ["windows-link"]
default = ["use-locks"]
